# Welcome to Jekyll!
#
# Toto je soubor s hlavním nastavením. Na začátku je nastavení proměných, které
# je třeba přispůsobit si pro váš web. Později v anglicky popsané části jsou více
# technické nastavení
#

title: Piráti - Karlovarský kraj # To co je napsané na tabu ve kterém je stránka.
email: karlovarsky@pirati.cz
description: Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
# dobré keywords jsou ty co lidé piší do googlu když hledají naši stránku
keywords: piráti, česká pirátská strana, svoboda, demokracie, karlovy vary, sokolov, cheb, karlovarský kraj

mediaStorage: karlovarsky

administrator:
  email: jan.suchanek@gmail.com, michaela.kleslova@pirati.cz, marek.krejpsky@pirati.cz, karel.specian@pirati.cz # mail(y), kam pujdou chybove vystupy; vice e-mailu oddelujte carkou

organization:
  name: Piráti - Karlovarský kraj
  shortName: Piráti - Karlovarský kraj
  email: karlovarsky@pirati.cz
  phone: 
  address: |
    Moskevská 60,
    Karlovy Vary
  residenceImg: https://a.pirati.cz/karlovarsky/img/epic/foto1.JPG
  mapLink: 
  redmineLink: 
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010

# Nastavení zobrazení tabulky kontaktů.
# Lze využít:
# 1) předdefinované typy (organizationEmail, organizationRedmineLink, organizationPhone, organizationTransparentAccount, organizationDataBox, piratiRootWebsite)
# 2) vlastní řádky - zde je nutné jako type dát `custom` a vyplnit `label` a `body`
contactSummaryItems:
  - type: organizationEmail
  - type: organizationRedmineLink
  - type: organizationPhone
  - type: organizationTransparentAccount
    includeMoreLink: true
  - type: organizationDataBox
#  - type: piratiRootWebsite
#  - type: custom
    #iconClass: fa fa-envelope
    #label: Vlastní řádek tabulky
    #body: <a href="http://example.com">link</a>

calendar:
  # For nice look of the calendar, make sure you get Google Calendar API key
  # and start the app with the env var `GOOGLE_CALENDAR_APIKEY=[myapikey] bundle exec jekyll serve`.
  # For deployment, contact website administrator to set you env variable.
  title: Krajský kalendář
  id: piratikvk@gmail.com
  page: https://calendar.google.com/calendar/embed?src=piratikvk%40gmail.com&ctz=Europe%2FPrague
calendarepic:
  title: Kalendář e-PIC
  page: https://calendar.google.com/calendar/embed?src=epic.kvary%40gmail.com&ctz=Europe%2FPrague
  
facebook:
  loadSDK: true
  #vyplně adresu vaší stranky, funguje pouze na stránky nikoliv skupiny
  profilePage: https://www.facebook.com/pirati.karlovarsko
  profilePageName: Pirátská strana - Karlovarský kraj
  appId: 1526197851008996

twitter:
  loadSDK: true
  profile: PiratskaStrana

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

gplus:
  profilePage: https://plus.google.com/u/0/+piratskastrana

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/karlovarsky.pirati.cz/
  branch: master
youtube:
  url: "https://www.youtube.com/channel/UC6zpUdw-MTT1WUBDo4K-nHA/videos"

#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

github_username:  pirati-web

sass:
  style: compressed
  sass_dir: _sass

theme: jekyll-theme-pirati

markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-environment-variables
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/

  program:
    output: true
    permalink: /volby/program/:path/

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
        - profile
        - people
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
         - garant
         - program

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-7.7.1/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass

styleguide_base_url: 'https://styleguide.pir-test.eu/latest/'
